"""agregar tablas de carrito y pedido

Revision ID: 0a436dbb2332
Revises: 47eb657e01a0
Create Date: 2026-05-13 18:07:06.572674

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '0a436dbb2332'
down_revision: Union[str, Sequence[str], None] = '47eb657e01a0'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
