"""v2 agregar tablas de carrito y pedido

Revision ID: b2b67665b74a
Revises: ddf77de0c450
Create Date: 2026-05-13 18:13:57.226450

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'b2b67665b74a'
down_revision: Union[str, Sequence[str], None] = 'ddf77de0c450'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
